### ISSUE TITLE
Release 2.1.0 ?

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#36]
I would like to use the possibility to export to jenkins-xml format in one of my downstream project. 

As discussed in https://github.com/selesse/jxlint/pull/35#issuecomment-496370162, for this I would need a release of the framework. I hope this is possible.

Please tell me if and how I can help.

**Comment by selesse** [comment]
2.1.0 has been [released](https://search.maven.org/search?q=a:jxlint).

As [mentioned](https://github.com/selesse/jxlint/pull/35#issuecomment-496498143), I would have  liked for you to update the project's [CHANGELOG](https://github.com/selesse/jxlint/blob/07650b6056e3c9006a40710332b7e3d999dd44f4/CHANGELOG.md) with all the changes in 2.0.0 and 2.1.0 since you wrote most of them.

**Comment by jmini** [comment]
Thank you a lot.

Sure I will write something for the CHANGELOG file.

**Comment by jmini** [comment]
The `2.1.0` tag is missing

**Comment by selesse** [comment]
Yes, I was hoping to include the CHANGELOG instructions in the tag.

I pushed a [2.1.0 tag](https://github.com/selesse/jxlint/releases/tag/2.1.0) without them.
